### ISSUE TITLE
Loading pdfs that are on local storage say memory card

### ISSUE THREAD

**Issue by WaiswaK** [yasiralijaved/XamarinFormsPdfViewer#1]
Would you please clarify how I can view pdfs in storage like memory card. It doesn't seem to work

**Comment by yasiralicare** [comment]
You can not make Shared XamarinForms code to display PDF from sdcard, because Android does support SDCard but not iOS. So, if you are going to use my example project to display PDF from SDCard, then you will have to modify the CustomRenderer in Android project.

Look at the variable **pathToFileFromSdCard**

```
protected override void OnElementChanged (ElementChangedEventArgs<Xamarin.Forms.WebView> e)
        {
            base.OnElementChanged (e);
            var pathToFileFromSdCard = ""; // Here you will put the absolute path of file from SDCard
            if (e.NewElement != null) {
                var customWebView = Element as CustomWebView;
                Control.Settings.AllowUniversalAccessFromFileURLs = true;
                Control.LoadUrl (string.Format ("file:///android_asset/pdfjs/web/viewer.html?file={0}", pathToFileFromSdCard));
            }
        }
```

**Comment by WaiswaK** [comment]
Thanks it has worked very grateful, only thing the pdf file name shouldn't have spaces but it has worked. Thanks

**Comment by yasiralicare** [comment]
welcome
